<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Procofa.Domain</RootNamespace>
    <!-- Sin PackageReference: el Domain no depende de ningún framework/librería externa (regla hexagonal). -->
  </PropertyGroup>

</Project>
